[GLOBAL]
type_flag: str,None,"polygons_shp,csv_label,csv_int,multiple_insitu,edit_flag,flag_ranges"
name_var: str,None

[polygons_shp]
input_var_lat: str,insitu_latitude
input_var_lon: str,insitu_longitude
input_shape: input_file,None
col_flag: str,None
other_col: strlist,None
flag_list: strlist,None

[csv_label]
required: input_csv,col_flag
input_csv: input_file,None
col_flag: str,None
flag_meanings: strlist,None
flag_values: intlist,None
col_date: str,None
col_time: str,None
format_col_date: str,None
format_col_time: str,None
col_datetime: str,None
format_col_datetime: str,None
time_variable: str,insitu_time
use_pow2: boolean,False

[csv_int]
required: input_csv,col_flag
input_csv: input_file,None
col_flag: str,None
flag_meanings: strlist,None
flag_values: intlist,None
col_date: str,None
col_time: str,None
format_col_date: str,None
format_col_time: str,None
col_datetime: str,None
format_col_datetime: str,None
time_variable: str,insitu_time
use_pow2: boolean,False


[multiple_insitu]
var_ref: str,insitu_time

[flag_ranges]
var_dim: str,None
flag_: strlist,None
range_: strlist,None
dim_change_: strlist,None 

[edit_flag]
required: var_flag
var_flag: str,None
flag_values: intlist,None
flag_meanings: strlist,None
default_value: int,0
flag_dims: strlist,satellite_id
attr_: strlist,None

##from algorithm_options, only for references
[expression]
required_args: input_path: input_file_nc
expression_: str,None
output_variable:str,None

[common_mu]
required_args: input_path: input_file_nc
output_variable: str,None
output_mode: str,only_variable,"only_variable,subset_file"
flag_among: str,flag_ac
flag_among_values: strlist,None
reference: str,sat_time,"sat_time,sat_date,sat_time_lat_lon,sat_date_lat_lon"
create_mu_variable: boolean,False
mu_valid_variable: str,None

[subset]
required_args: input_path: input_file_nc, output: output_file_nc
type_subset: str,basic_filter,"basic_filter"
basic_filter: str,None

[brdf]
required_args: input_path: input_file_nc
output_variable: str,None
brdf_model: str,O25,"Morel,O25"
wl_var: str, None
rrs_var: str, None
sza_var: str, None
vza_var: str, None
raa_var: str, None
vaa_var: str, None
saa_var: str, None

[bal_chl]
required_args: input_path: input_file_nc
version: str,202411,"202211,202411,BOTH"
